Controllers/DetailArtistController.cs
using MusicViet.DataModel;
using MusicViet.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicViet.Controllers
{
    public class DetailArtistController : Controller
    {
        MusicDbContext db = new MusicDbContext();
        //
        // GET: /DetailArtist/
        public ActionResult Detail(int id, string artist)
        {
            
            Artist art = new Artist();
            if (artist == "singer")
            {
                var NameArtist = db.Singers.SingleOrDefault(x=>x.SingerId == id).SingerName;
                var PathArtist = db.Singers.SingleOrDefault(x => x.SingerId == id).SingerPic;
                var story = db.Singers.SingleOrDefault(x => x.SingerId == id).SingerStory;
                var SongOfArtist = db.Songs.Where(x => x.SingerId == id).ToList();
                art.Story = story;
               art.NameArtist = NameArtist;
               art.PathArtist = PathArtist;
               art.listSong = SongOfArtist;
              
            }
            if (artist == "musician")
            {
                var Artist = db.Musicians.SingleOrDefault(x => x.MusicianId == id).MusicianName;
                var PathArtist = db.Musicians.SingleOrDefault(x => x.MusicianId == id).MusicianPic;
                var story = db.Musicians.SingleOrDefault(x => x.MusicianId == id).MusicianStory;
                var SongOfArtist = db.Songs.Where(x => x.MusicianId == id).ToList();
                art.NameArtist = Artist[1].ToString();
                art.PathArtist = Artist[2].ToString();
                art.listSong = SongOfArtist;
                art.Story = story;
            }
            ViewBag.Artist = art;
            return View();
        }
	}
}

Controllers/GenresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicViet.Controllers
{
    public class GenresController : Controller
    {
        //
        // GET: /Genres/
        public ActionResult TheLoai()
        {
            return View();
        }
        public ActionResult TheLoai(string name)
        {
            return View();
        }
	}
}

Views/Genres/TheLoai.cshtml
@{
    ViewBag.Title = "TheLoai";
    Layout = "~/Views/Shared/LayoutShare.cshtml";
}
<div class="ms-home-top">
    <div class="ms-bxh-tophit">
        <div class="ms-bxh-infotophit">
            <h3>
                BẢNG XẾP HẠNG BÀI HÁT
            </h3>
            Bảng xếp hảng là danh sách những ca khúc hot nhất hiện tại của từng thể loại nhạc, được hệ thống tự động đề xuất dựa trên
            thông tin số liệu lượt nghe và lượt chia sẻ của từng bài hát trên cả desktop và mobile. Dữ liệu sẽ được
            lấy trong 30 ngày gần nhất và được cập nhật liên tục.
        </div>
        <div class="ms-bxh-listtophit">
            <ul>
                @*@foreach (var item in ViewBag.GetBHX as List<MusicViet.Models.ListSong>)
                {
                    <li>
                        <div class="ms-bxh-bhhot">
                            <span class="bxh-bh-stt">@(stt++)</span>
                            <div class="bxh-bh-img">
                                <img src="@Url.Content(item.PathSinger)" alt="">
                            </div>
                            <div class="bxh-bh-name">
                                <a href="#">@item.SongTitle</a>

                                @Html.ActionLink(item.SingerName, "Detail", "DetailArtist", new { id = item.SingerId, artist = "singer" }, null)
                            </div>
                            <div class="bxh-bh-luotnghe">
                                <span class="glyphicon glyphicon-headphones"></span>@item.Views
                            </div>
                            <div class="bxh-bh-infoplus">
                                <a href="@Url.Content(item.PathMusic)" download>
                                    <span class="glyphicon glyphicon-download-alt"></span>
                                </a>
                                <a href="#">
                                    <span class="glyphicon glyphicon-plus"></span>
                                </a>
                            </div>

                        </div>
                    </li>
                }*@

            </ul>
        </div>
        <div></div>
    </div>
    @RenderPage("../Shared/BHXGenres.cshtml")
</div>
<div class="ms-home-bottom">

</div>