Controllers/FavoriteController.cs
using MusicViet.DataModel;
using MusicViet.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicViet.Controllers
{
    public class FavoriteController : Controller
    {
        MusicDbContext db = new MusicDbContext();
        //
        // GET: /Favorite/
        public ActionResult Favorite()
        {
            if (Session["userId"]!=null)
            {
                var userid = Convert.ToInt32(Session["userId"]);
                ViewBag.MyFavorite = (from ac in db.Accounts
                                      join fav in db.Favorites on ac.UserId equals fav.UserId
                                      join song in db.Songs on fav.SongId equals song.SongId
                                      where ac.UserId == userid
                                      select new ListSong
                                      {
                                      
                                          SongTitle = song.SongTitle,
                                          Views = song.Views,
                                          PathMusic = song.PathMusic,
                                          Id = song.SongId
                                      }).ToList();
                return View();
            }
            return RedirectToAction("/");   
        }
	}
}

Views/Shared/BHXGenres.cshtml
<div class="ms-bxh-theloai">
    <h4>Bảng xếp hạng theo thể loại</h4>
    <ul>
        <li><a href="#"><img src="~/ImageUpload/bolero.png" /></a></li>
        <li><a href="#"><img src="~/ImageUpload/nhac%20tre.png" /></a></li>
        <li><a href="#"><img src="~/ImageUpload/nhac%20vang.png" /></a></li>
        <li><a href="#"><img src="~/ImageUpload/nhac%20que%20huong.png" /></a></li>
        <li><a href="#"><img src="~/ImageUpload/nhac%20cach%20mang.png" /></a></li>
    </ul>
</div>

Views/Shared/Header.cshtml
<div class="ms-header-logo">
    <img width="120" src="~/Content/Images/logo.svg" />
</div>

@if (Session["userId"] == null)
{
    <div class="ms-header-dangnhap">
        @Html.ActionLink("Đăng nhập", "Login", "Home")
    </div>
}
else
{
    <div class="ms-dadangnhap">
        <span>Chào bạn @Session["fullname"]</span>
        <div class="dropdown">
            <button class="btn dropdown-toggle" type="button" data-toggle="dropdown" style="background-color:#5743bd;">
                <i class="fa fa-bars" aria-hidden="true"></i>
                <span class="caret"></span>
            </button>
            <ul class="dropdown-menu dropdown-menu-right">
                <li><a href="#">Đổi mật khẩu</a></li>
                <li><a href="#">Xem thông tin cá nhân</a></li>
                <li>@Html.ActionLink("Bài hát yêu thích", "Favorite", "Favorite")</li>
                <li>@Html.ActionLink("Thoát","Logout","Home")</li>
            </ul>
        </div>
    </div>
}

Views/Shared/LayoutShare.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Nhạc của mình</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
    <link rel='stylesheet prefetch' href='https://fonts.googleapis.com/css?family=Roboto:400'>
    <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/node-waves/0.7.5/waves.min.css'>
    <link rel='stylesheet prefetch' href='https://michael-zhigulin.github.io/mz-codepen-projects/Material%20Design%20UI%20Audio%20Player/font/font.css'>
    <link href="~/Content/Css/style.css" rel="stylesheet" />
    <link href="~/Content/Css/bxh.css" rel="stylesheet" />
    <link href="~/Content/Css/AudioCss.css" rel="stylesheet" />
    <link href="~/Content/Css/Detail.css" rel="stylesheet" />
    <link href="~/Content/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <style>
        a:hover {
            text-decoration: none !important;
        }
        .ms-footer {
            background: #212529; /* nền tối */
            color: #fff;
        }
    </style>
</head>

<body>
    <div class="ms-home-layout">
        <div class="ms-header">
            @RenderPage("Header.cshtml")
        </div>
        <div class="ms-menu">
            @RenderPage("MenuHeader.cshtml")
        </div>
        @RenderBody()
        <footer class="ms-footer text-center py-3 mt-5">
            <div class="container">
                <p class="mb-0 text-white-50">
                    🎵 Website nghe nhạc online miễn phí © @DateTime.Now.Year
                </p>
            </div>
        </footer>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="~/Content/bootstrap/js/bootstrap.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#myCarousel').carousel({
                interval: 2000
            });

            var clickEvent = false;
            $('#myCarousel').on('click', 'subimg li', function () {
                clickEvent = true;
                $('subimg" li').removeClass('active');
                $(this).parent().addClass('active');
            }).on('slid.bs.carousel', function (e) {
                if (!clickEvent) {
                    var count = $('subimg').children().length - 1;
                    var current = $('subimg li.active');
                    current.removeClass('active').next().addClass('active');
                    var id = parseInt(current.data('slide-to'));
                    if (count == id) {
                        $('subimg li').first().addClass('active');
                    }
                }
                clickEvent = false;
            });
        });
    </script>
</body>

</html>

Views/Shared/MenuHeader.cshtml
<ul>
    <li>
        <a href="/">
            <i class="fa fa-home" aria-hidden="true"></i>Trang chủ
        </a>
    </li>
    <li>
        <a href="">Thể loại</a>
        <ul class="ms-menu-sub">
            <li>
                <a href="#">Nhạc trẻ</a>
            </li>
            <li>
                <a href="#">Nhạc cách mạng</a>
            </li>
            <li>
                <a href="#">Nhạc đồng quê</a>
            </li>
            <li>
                
                <a href="#">Bolero</a>
            </li>
            <li>
                <a href="#">Nhạc vàng</a>
            </li>
        </ul>
    </li>
    <li>
        Nhạc sĩ
    </li>
    <li>Ca sĩ</li>
    <li><a href="">TOP 100</a>
        <ul class="ms-menu-sub">
            <li>
                <a href="~/BXH/BXH">TOP BXH</a>
            </li>
            <li>
                <a href="#">Nhạc trẻ</a>
            </li>
            <li>
                <a href="#">Nhạc cách mạng</a>
            </li>
            <li>
                <a href="#">Nhạc đồng quê</a>
            </li>
            <li>

                <a href="#">Bolero</a>
            </li>
            <li>
                <a href="#">Nhạc vàng</a>
            </li>
        </ul>
    </li>
    <li>Hit</li>
</ul>