Controllers/DetailSongController.cs
using MusicViet.DataModel;
using MusicViet.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicViet.Controllers
{
    public class DetailSongController : Controller
    {
        MusicDbContext db = new MusicDbContext();
        //
        // GET: /DetailSong/
        public ActionResult Detail(int id)
        {
            Song song1 = new Song();
            // Lay bai hat tu cdsl
            song1 = db.Songs.Where(s => s.SongId == id).FirstOrDefault<Song>();
            // Lay so luot view cho bai hat va tang view len 1
            var views = (from song in db.Songs
                         join sing in db.Singers on song.SingerId equals sing.SingerId
                         select new ListSong
                         {
                             Id = song.SongId,
                             SongTitle = song.SongTitle,
                             SingerName = sing.SingerName,
                             Views = song.Views,
                             PathMusic = song.PathMusic
                         }).SingleOrDefault(x => x.Id == id).Views;
            
            song1.Views = views + 1;

            ViewBag.SongTitle = db.Songs.SingleOrDefault(x => x.SongId == id).SongTitle;
            ViewBag.PathMusic = db.Songs.SingleOrDefault(x => x.SongId == id).PathMusic;
            ViewBag.SingerName = (from song in db.Songs
                                  join sing in db.Singers on song.SingerId equals sing.SingerId
                                  select new ListSong
                                  {
                                      Id = song.SongId,
                                      SongTitle = song.SongTitle,
                                      SingerName = sing.SingerName,
                                      Views = song.Views,
                                      PathMusic = song.PathMusic
                                  }).SingleOrDefault(x => x.Id == id).SingerName;
            // Cap nhat luot view vao CSDL
            ViewBag.Views = views + 1;

            db.Entry(song1).State = EntityState.Modified;

            db.SaveChanges();


            return View();
        }
    }
}

Controllers/FavoriteController.cs
using MusicViet.DataModel;
using MusicViet.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MusicViet.Controllers
{
    public class FavoriteController : Controller
    {
        MusicDbContext db = new MusicDbContext();
        //
        // GET: /Favorite/
        public ActionResult Favorite()
        {
            if (Session["userId"]!=null)
            {
                var userid = Convert.ToInt32(Session["userId"]);
                ViewBag.MyFavorite = (from ac in db.Accounts
                                      join fav in db.Favorites on ac.UserId equals fav.UserId
                                      join song in db.Songs on fav.SongId equals song.SongId
                                      where ac.UserId == userid
                                      select new ListSong
                                      {
                                      
                                          SongTitle = song.SongTitle,
                                          Views = song.Views,
                                          PathMusic = song.PathMusic,
                                          Id = song.SongId
                                      }).ToList();
                return View();
            }
            return RedirectToAction("/");   
        }
	}
}

Views/Favorite/Favorite.cshtml
@{
    ViewBag.Title = "Favorite";
    Layout = "~/Views/Shared/LayoutShare.cshtml";
}

@if (ViewBag.MyFavorite.Count > 0)
{
    <h2>Danh sách bài hát yêu thích của bạn: </h2>
    <ul>
        @foreach (var item in (IEnumerable<MusicViet.Models.ListSong>) ViewBag.MyFavorite )
        {
            <li>
                <div class="artist-bhhot">
                    <div class="artist-img">
                        <img src="~/Content/Images/music.jpg" />
                    </div>
                    <div class="artist-name">
                        @Html.ActionLink(item.SongTitle, "Detail", "DetailSong", new { id = item.Id }, null)
                    </div>
                    <div class="artist-luotnghe">
                        <span class="glyphicon glyphicon-headphones"></span>@item.Views
                    </div>
                    <div class="artist-infoplus">
                        <a href="Url.Content(item.PathMusic)" download>
                            <span class="glyphicon glyphicon-download-alt"></span>
                        </a>
                    </div>

                </div>
            </li>
        }
    </ul>
}
else
{
    <h2>Hiện tại bạn chưa có bài hát yêu thích nào</h2>
}