Areas/Admin/Controllers/MusicGenresController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using MusicViet.DataModel;
using System.IO;

namespace MusicViet.Areas.Admin.Controllers
{
    public class MusicGenresController : Controller
    {
        private MusicDbContext db = new MusicDbContext();

        // GET: /Admin/MusicGenres/
        public ActionResult Index()
        {
            return View(db.MusicGenres.ToList());
        }

        // GET: /Admin/MusicGenres/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MusicGenres musicgenres = db.MusicGenres.Find(id);
            if (musicgenres == null)
            {
                return HttpNotFound();
            }
            return View(musicgenres);
        }

        // GET: /Admin/MusicGenres/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Admin/MusicGenres/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="MusicGenresName,DesMusicGenres")] MusicGenres musicgenres, HttpPostedFileBase Image)
        {


            try
            {
                if (Image.ContentLength > 0)
                {
                    string filename = Path.GetFileName(Image.FileName);
                    string path = Path.Combine(Server.MapPath("~/ImageUpload/"), filename);
                    Image.SaveAs(path);
                    musicgenres.MusicGenresPic = "~/ImageUpload/" + filename;
                    db.MusicGenres.Add(musicgenres);
                    db.SaveChanges();
                    return RedirectToAction("Index");


                }
            }
            catch (Exception)
            {
                ViewBag.Error = "Loi upload File";
                return View();
            }
            return View();
        }

        // GET: /Admin/MusicGenres/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MusicGenres musicgenres = db.MusicGenres.Find(id);
            if (musicgenres == null)
            {
                return HttpNotFound();
            }
            return View(musicgenres);
        }

        // POST: /Admin/MusicGenres/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="MusicGenresId,MusicGenresName,MusicGenresPic,DesMusicGenres")] MusicGenres musicgenres)
        {
            if (ModelState.IsValid)
            {
                db.Entry(musicgenres).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(musicgenres);
        }

        // GET: /Admin/MusicGenres/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MusicGenres musicgenres = db.MusicGenres.Find(id);
            if (musicgenres == null)
            {
                return HttpNotFound();
            }
            return View(musicgenres);
        }

        // POST: /Admin/MusicGenres/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            MusicGenres musicgenres = db.MusicGenres.Find(id);
            db.MusicGenres.Remove(musicgenres);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Admin/Views/MusicGenres/Create.cshtml
@model MusicViet.DataModel.MusicGenres



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm("Create", "MusicGenres", FormMethod.Post, new { enctype = "multipart/form-data" })) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>MusicGenres</h4>
            <hr />
            @Html.ValidationSummary(true)
    
            <div class="form-group">
                @Html.LabelFor(model => model.MusicGenresName, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MusicGenresName)
                    @Html.ValidationMessageFor(model => model.MusicGenresName)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.MusicGenresPic, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <input type="file" name="Image" />
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.DesMusicGenres, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.DesMusicGenres, new { @class = "form-control", @rows = "10" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Quay Lại", "Index")
    </div>
</body>
</html>

Areas/Admin/Views/MusicGenres/Delete.cshtml
@model MusicViet.DataModel.MusicGenres



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Bạn có muốn xóa Thể Loại này không</h3>
    <div>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.MusicGenresName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.MusicGenresName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.MusicGenresPic)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.MusicGenresPic)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.DesMusicGenres)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.DesMusicGenres)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index", new object { }, new { @class = "btn btn-default", role = "button" })
            </div>
        }
    </div>
</body>
</html>

Areas/Admin/Views/MusicGenres/Details.cshtml
@model MusicViet.DataModel.MusicGenres



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>MusicGenres</h4>
    	<hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.MusicGenresName)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.MusicGenresName)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.MusicGenresPic)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.MusicGenresPic)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.DesMusicGenres)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.DesMusicGenres)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.MusicGenresId }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Areas/Admin/Views/MusicGenres/Edit.cshtml
@model MusicViet.DataModel.MusicGenres

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>MusicGenres</h4>
            <hr />
            @Html.ValidationSummary(true)
            @Html.HiddenFor(model => model.MusicGenresId)
    
            <div class="form-group">
                @Html.LabelFor(model => model.MusicGenresName, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MusicGenresName)
                    @Html.ValidationMessageFor(model => model.MusicGenresName)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.MusicGenresPic, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MusicGenresPic)
                    @Html.ValidationMessageFor(model => model.MusicGenresPic)
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.DesMusicGenres, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.DesMusicGenres)
                    @Html.ValidationMessageFor(model => model.DesMusicGenres)
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Areas/Admin/Views/MusicGenres/Index.cshtml
@model IEnumerable<MusicViet.DataModel.MusicGenres>



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <h2 style="font-size:20px; text-align:center; font-weight: 600;">DANH SÁCH THỂ LOẠI NHẠC</h2>
    <p>
        @Html.ActionLink("Thêm mới", "Create", new object { }, new { @class = "btn btn-info", role = "button" })
    </p>
    <table class="table table-hover">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.MusicGenresName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.MusicGenresPic)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DesMusicGenres)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.MusicGenresName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.MusicGenresPic)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DesMusicGenres)
                    </td>
                    <td style="width:15%;">
                        @Html.ActionLink("Edit", "Edit", new { id=item.MusicGenresId }) |
                        @Html.ActionLink("Details", "Details", new { id=item.MusicGenresId }) |
                        @Html.ActionLink("Delete", "Delete", new { id=item.MusicGenresId })
                    </td>
                </tr>
    }
        </tbody>
    </table>
</body>
</html>